# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2607dad2b25f7aa4ccc2c68c5b2daaa08f33323e6c7982fdead388364059ebfe52d29f974b7b120f3653512d5923281b00088cc9361e9a897ddd1512ee1f74c3

test:
  secret_key_base: 53b6a0b371f85928ddcfa63a4f2d7f7bdccffd2ad81fece0deb6a3da42974a6a1b9592be6ddebf9de5ca895212f531919d413e1364963cd5ee5cc92a22e27a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
